### ISSUE TITLE
Stop breaking your npm shit dude

### ISSUE THREAD

**Issue by LorenzoOpWerk** [mailslurp/mailslurp-client#11]

**Comment by KrisTemmerman** [comment]
I agree

**Comment by jackmahoney** [comment]
Sorry guys! I'm really sorry about this. 

It was because the NPM client linked to a Github hash but old hashes were being overwritten by our CI pipeline. We didn't discover this until people like you reported it. Thank you again!

We have now removed any github dependencies from the package pinned the versions semantically.

Please try the latest version as this will remain stable (I promise!) from now on.

Jack

**Comment by jackmahoney** [comment]
cc @KrisTemmerman @LorenzoOpWerk

**Comment by KrisTemmerman** [comment]
Hey dude, thanks for fixing !
